[package]
name = "catscope-rust-bot"
version = "0.3.5"
edition = "2021"

[dependencies]

#orca_whirlpools = "8"hex = "0.4.3"
wit-bindgen = "0.41"
paste = "1.0.15"
solana-sdk = "3.0.0"
solana-sdk-ids = "3.0.0"
solana-compute-budget-interface = "3.0.0"
spl-token = { version = "9", features = ["no-entrypoint"] }
spl-associated-token-account = "8"
solana-system-interface = { version = "2.0.0", features = ["bincode"] }
wincode = { version = "0.3.1", features = ["derive"] }
bincode = { version = "2.0.1", features = ["serde"] }
chacha20poly1305 = "0.10"
hkdf = "0.12"
sha2 = "0.10"
curve25519-dalek = { version = "4", default-features = false, features = [
  "alloc",
] }
x25519-dalek = { version = "2", default-features = false, features = [
  "static_secrets",
] }
#catscope-zerohop = { version = "0.1.3", features = ["wasmonly"] }
serde = "1"
serde_json = "1"
ethnum = "1.5"

orca_whirlpools_core = { version = "2.1.0" }

[build-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bs58 = "0.5"

[dev-dependencies]
solana-rpc-client = "3.0"
serde = "1"
serde_json = "1"

[lib]
crate-type = ["cdylib"]

[profile.release]
#opt-level = "z"
opt-level = 1
lto = true
codegen-units = 1
panic = "abort"
debug = 1


[patch.crates-io]
orca_whirlpools_core = { path = "vendor/orca_whirlpools_core" }
orca_whirlpools_macros = { path = "vendor/orca_whirlpools_macros" }
#catscope-zerohop = { path = "../catscope-zerohop" }
