[package]
name = "catscope-bot-guest"
version = "0.1.6"
edition = "2024"
license = "MIT"
authors = ["Maintainers <maintainers@noncepad.com>"]
rust-version = "1.89"

[dependencies]
wit-bindgen = "0.44.0"
wit-bindgen-rt = { version = "0.44.0", features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "catscope:witbot"

[package.metadata.component.dependencies]
[package.metadata.component.target]
path = "wit"
